/**
 * Dữ liệu mặc định cho portfolio — được seed vào DB lần đầu chạy.
 * Sau đó chỉnh sửa qua Admin Panel.
 */

module.exports = {
  // ─── Thông tin cá nhân ──────────────────────────────────────────
  profile: {
    name:        'Đinh Hoàng Trung Khánh',
    name_short:  'ĐHTK',
    title_en:    'Frontend Developer',
    title_vi:    'Lập trình viên giao diện',
    tagline_en:  'Crafting interfaces that people love to use',
    tagline_vi:  'Xây dựng giao diện người dùng yêu thích',
    bio_vi:      'Xin chào! Tôi là Đinh Hoàng Trung Khánh, Frontend Developer với niềm đam mê tạo ra những giao diện vừa đẹp mắt vừa hoạt động mượt mà.',
    bio_en:      'I specialise in building performant, accessible React applications with a keen eye for design detail.',
    email:       'khanh@example.com',
    github:      'https://github.com/yourusername',
    linkedin:    'https://linkedin.com/in/yourprofile',
    location:    'Hà Nội, Việt Nam',
    available:   true,
    years_exp:   '2+',
    projects_count: '15+',
    github_stars: '5k+',
  },

  // ─── Kỹ năng ────────────────────────────────────────────────────
  skills: [
    {
      id: 1,
      num: '01 / 04',
      icon: '⚛️',
      title: 'UI Frameworks',
      title_vi: 'Framework giao diện',
      pills: ['React', 'Next.js', 'Vue 3', 'Nuxt', 'Astro'],
    },
    {
      id: 2,
      num: '02 / 04',
      icon: '🎨',
      title: 'Styling & Design',
      title_vi: 'Thiết kế & CSS',
      pills: ['Tailwind CSS', 'CSS Modules', 'Framer Motion', 'GSAP', 'Figma', 'SCSS'],
    },
    {
      id: 3,
      num: '03 / 04',
      icon: '🔧',
      title: 'Language & Build',
      title_vi: 'Ngôn ngữ & Build tool',
      pills: ['TypeScript', 'JavaScript ES2024', 'Vite', 'Webpack', 'Vitest', 'Storybook'],
    },
    {
      id: 4,
      num: '04 / 04',
      icon: '🚀',
      title: 'Backend & DevOps',
      title_vi: 'Backend & Triển khai',
      pills: ['Node.js', 'Express', 'REST API', 'PostgreSQL', 'Docker', 'Vercel', 'Git'],
    },
  ],

  // ─── Kinh nghiệm ────────────────────────────────────────────────
  experience: [
    {
      id: 1,
      period: '2024 — Hiện tại · Present',
      role: 'Frontend Developer',
      role_vi: 'Lập trình viên Giao diện',
      company: 'Công ty ABC · Full-time',
      desc_vi: 'Phát triển và duy trì ứng dụng web cho 30,000+ người dùng. Tối ưu Core Web Vitals đạt điểm 95+ trên Lighthouse. Xây dựng Design System dùng chung cho toàn team.',
      desc_en: 'Building and maintaining web apps for 30k+ users. Achieved 95+ Lighthouse score. Built shared Design System.',
      chips: ['React', 'TypeScript', 'Next.js', 'Tailwind'],
    },
    {
      id: 2,
      period: '2023 — 2024',
      role: 'Junior Frontend Developer',
      role_vi: 'Lập trình viên Giao diện Mới vào nghề',
      company: 'Startup XYZ · Full-time',
      desc_vi: 'Tham gia xây dựng 2 sản phẩm từ giai đoạn đầu. Thiết kế và phát triển landing page tăng conversion rate 35%.',
      desc_en: 'Built 2 products from scratch. Designed landing pages that improved conversion by 35%.',
      chips: ['Vue 3', 'Nuxt', 'SCSS', 'Figma'],
    },
    {
      id: 3,
      period: '2022 — 2023',
      role: 'Intern Frontend Developer',
      role_vi: 'Thực tập sinh Lập trình Giao diện',
      company: 'Agency DEF · Part-time',
      desc_vi: 'Xây dựng 10+ website cho khách hàng. Học hỏi quy trình làm việc agile, code review, và kỹ năng giao tiếp với khách hàng.',
      desc_en: 'Built 10+ client websites. Learned agile workflow, code review, and client communication.',
      chips: ['HTML/CSS', 'JavaScript', 'WordPress'],
    },
    {
      id: 4,
      period: '2019 — 2023',
      role: 'Cử nhân Công nghệ Thông tin',
      role_vi: 'B.Sc. Information Technology',
      company: 'Đại học Bách Khoa Hà Nội · HUST',
      desc_vi: 'Tốt nghiệp loại Giỏi. Đồ án tốt nghiệp đạt giải Nhất hackathon toàn trường — ứng dụng hỗ trợ học ngoại ngữ sử dụng AI.',
      desc_en: 'Graduated with distinction. Final project won 1st place at university hackathon — AI language learning app.',
      chips: ['GPA 3.6/4.0', 'Hackathon Winner'],
    },
  ],

  // ─── Dự án ──────────────────────────────────────────────────────
  projects: [
    {
      id: 1,
      featured: true,
      num: '001 / Featured',
      tag: '✦ Dự án nổi bật · Featured Project',
      title: 'LangAI — Học Ngoại Ngữ',
      title_vi: 'AI-Powered Language Learning App',
      desc_vi: 'Ứng dụng học ngoại ngữ thông minh sử dụng AI để cá nhân hoá lộ trình học, tạo bài tập theo điểm yếu của từng người. Đoạt giải Nhất hackathon toàn trường với 500+ người dùng đang hoạt động.',
      desc_en: 'Smart language learning app using AI to personalise learning paths. Won university hackathon 1st place with 500+ active users.',
      icon: '🌐',
      github: 'https://github.com/yourusername/lang-ai',
      live: '',
      stack: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Claude API', 'Vercel'],
    },
    {
      id: 2,
      featured: false,
      num: '002',
      tag: 'Open Source · Mã nguồn mở',
      title: 'KhanhUI — Component Library',
      title_vi: 'Thư viện Component React',
      desc_vi: 'Bộ 50+ React component được thiết kế kỹ lưỡng, hỗ trợ dark/light mode, fully accessible (WCAG AA). 1.2k ⭐ GitHub.',
      desc_en: '50+ carefully designed React components. Dark/light mode, WCAG AA accessible. 1.2k GitHub stars.',
      icon: '🎨',
      github: 'https://github.com/yourusername/uikit',
      live: '',
      stack: ['React', 'TypeScript', 'Storybook', 'npm'],
    },
    {
      id: 3,
      featured: false,
      num: '003',
      tag: 'Tool · Công cụ',
      title: 'PerfWatch — Web Vitals Monitor',
      title_vi: 'Giám sát hiệu năng trang web',
      desc_vi: 'Dashboard realtime theo dõi Core Web Vitals, Lighthouse score và performance budget. Tích hợp CI/CD alerts.',
      desc_en: 'Realtime dashboard tracking Core Web Vitals, Lighthouse score, and performance budget with CI/CD alerts.',
      icon: '⚡',
      github: 'https://github.com/yourusername/devtools',
      live: '',
      stack: ['Next.js', 'Recharts', 'Puppeteer'],
    },
    {
      id: 4,
      featured: false,
      num: '004',
      tag: 'Template · Mẫu',
      title: 'Portfolio Template',
      title_vi: 'Mẫu trang cá nhân miễn phí',
      desc_vi: 'Template portfolio miễn phí với 3 theme, responsive hoàn toàn, SEO sẵn có. 800+ lượt fork trên GitHub.',
      desc_en: 'Free portfolio template with 3 themes, fully responsive, SEO ready. 800+ GitHub forks.',
      icon: '📄',
      github: 'https://github.com/yourusername/portfolio-template',
      live: '',
      stack: ['Astro', 'Tailwind', 'MDX'],
    },
  ],
};